from typing import Optional, Dict, Any
from puzzlekit.core.grid import Grid
from .common import (verify_exact, verify_target_content, verify_target_set, verify_lines, verify_digits, verify_bijective, verify_wall)

GRID_VERIFIERS = {
    "abc_end_view": verify_exact,
    "akari": lambda a, b: verify_target_content(a, b, 'o'),
    "balance_loop": lambda a, b: verify_lines(a, b),
    "binairo": verify_exact,
    "bosanowa": verify_exact,
    "buraitoraito": lambda a, b: verify_target_content(a, b, "*"),
    "butterfly_sudoku": verify_exact,
    "clueless_1_sudoku": verify_exact,
    "clueless_2_sudoku": verify_exact,
    "country_road": verify_lines,
    "detour": verify_lines,
    "dominos": verify_bijective,
    "double_back": verify_lines,
    "entry_exit": verify_lines,
    "eulero":verify_exact,
    "even_odd_sudoku":verify_exact,
    "fobidoshi": lambda a, b: verify_target_content(a, b, 'o'),
    "fuzuli": verify_digits,
    "gappy": lambda a, b: verify_target_content(a, b, 'x'),
    "gattai_8_sudoku":verify_exact,
    "grand_tour": verify_wall,
    "hakyuu": verify_digits,
    "heyawake": lambda a, b: verify_target_content(a, b, 'x'),
    "hitori": lambda a, b: verify_target_content(a, b, 'x'),
    "jigsaw_sudoku":verify_exact,
    "kakurasu": lambda a, b: verify_target_content(a, b, 'x'),
    "kakuro": verify_digits,
    "killer_sudoku":verify_exact,
    "kuroshuto": lambda a, b: verify_target_content(a, b, 'x'),
    "linesweeper": verify_lines,
    "magnetic": lambda a, b: verify_target_set(a, b, { "-", "+", "x" }),
    "masyu": verify_lines,
    "minesweeper": lambda a, b: verify_target_content(a, b, 'x'),
    "mosaic": lambda a, b: verify_target_content(a, b, 'x'),
    "munraito":verify_exact,
    "nondango":verify_exact,
    "nonogram": lambda a, b: verify_target_content(a, b, 'x'),
    "norinori": lambda a, b: verify_target_content(a, b, 'x'),
    "one_to_x": verify_digits,
    "patchwork": verify_digits,
    "pfeilzahlen": verify_lines,
    "pills": verify_bijective,
    "renban": verify_digits,
    "samurai_sudoku":verify_exact,
    "shikaku": verify_bijective,
    "shogun_sudoku":verify_exact,
    "simple_loop": verify_lines,
    "slitherlink": verify_wall,
    "sohei_sudoku":verify_exact,
    "square_o": lambda a, b: verify_target_content(a, b, 'x'),
    "starbattle": lambda a, b: verify_target_content(a, b, 'x'),
    "str8t": verify_digits,
    "sudoku":verify_exact,
    "suguru": verify_digits,
    "sumo_sudoku":verify_exact,
    "tenner_grid":verify_exact,
    "tent": lambda a, b: verify_target_content(a, b, 'o'),
    "terra_x": verify_digits,
    "thermometer":verify_exact,
    "tile_paint": lambda a, b: verify_target_content(a, b, "#"),
    "windmill_sudoku":verify_exact,
    "yajilin": verify_lines,
}

def grid_verifier(puzzle_type: str, a: Grid, b: Grid) -> bool:
    verifier = GRID_VERIFIERS.get(puzzle_type)
    if verifier is None:
        raise ValueError(f"No verifier defined for puzzle type: {puzzle_type}")
    return verifier(a, b)