name: Publish to PyPI

# Trigger: only when a tag starting with 'v' is pushed to the repository
# For example: git push origin v0.1.0 (will trigger)
on:
  push:
    tags:
      - "v*"

jobs:
  build-n-test:
    uses: ./.github/workflows/reusable_build_test.yml
    with:
      python_version: "3.10"
      upload_artifact: true
      build_package: true

  # Second stage: publish to PyPI
  # Only run if the build-n-test stage succeeds
  publish-to-pypi:
    name: Publish to PyPI
    needs: build-n-test # Dependency: must wait for tests to pass
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/puzzlekit
    permissions:
      id-token: write # This line is important for new Trusted Publishing, but also compatible with Token method

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
